# Generated by Django 4.1.2 on 2022-10-19 06:21

import commitment.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentCategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentNameModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commitment_date', models.DateTimeField(blank=True, default=commitment.models.next_day_datetime)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentcategorymodel')),
                ('commitment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentnamemodel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentGraphDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_done', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
