# Generated by Django 4.1.2 on 2022-12-28 18:34

import commitment.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('time_to_start', models.TimeField(null=True)),
                ('commitment_date', models.DateTimeField(blank=True, default=commitment.models.next_day_datetime)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('commitment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentnamemodel')),
            ],
        ),
    ]
