# Generated by Django 4.1.2 on 2022-10-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitmentmodel',
            old_name='category',
            new_name='category_id',
        ),
    ]
