# Generated by Django 4.1.2 on 2023-01-16 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 22, 23, 31, 23, 791231)),
        ),
    ]
