# Generated by Django 4.1.2 on 2023-07-29 06:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2023, 7, 30, 6, 11, 38, 147758)
            ),
        ),
    ]
