# Generated by Django 4.1.2 on 2022-10-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0002_rename_category_commitmentmodel_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitmentmodel',
            old_name='commitment_name',
            new_name='commitment_name_id',
        ),
    ]
