# Generated by Django 4.1.2 on 2023-01-17 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commitment", "0003_alter_usernumberofcommitmentfornextweekmodel_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernumberofcommitmentfornextweekmodel",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2023, 1, 22, 11, 27, 13, 602977)
            ),
        ),
    ]
