# Generated by Django 4.1.2 on 2022-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0003_alter_exercisemodel_time_to_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='did_speak_before',
            field=models.BooleanField(default=False),
        ),
    ]
