# Generated by Django 4.1.2 on 2022-10-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0004_alter_commitmentcategorymodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitmentgraphdatamodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commitmentmodel',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='commitmentmodel',
            old_name='commitment_name_id',
            new_name='commitment_name',
        ),
        migrations.RenameField(
            model_name='commitmentmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commitmentnamemodel',
            old_name='category_id',
            new_name='category',
        ),
    ]
