# Generated by Django 4.1.2 on 2022-10-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0005_rename_user_id_commitmentgraphdatamodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentnamemodel',
            name='category',
            field=models.ForeignKey(error_messages='c', null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentcategorymodel'),
        ),
        migrations.AlterField(
            model_name='commitmentnamemodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
