# Generated by Django 4.1.2 on 2023-08-02 17:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitment", "0005_alter_usercommitmentsfornextweekmodel_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2023, 8, 6, 17, 12, 12, 945806)
            ),
        ),
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="min_no_of_exercise_commitments",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="min_no_of_food_commitments",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="min_no_of_water_commitments",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
