# Generated by Django 4.1.2 on 2023-01-04 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_individualexercisemodel_and_more'),
        ('commitment', '0005_exercisemodel_did_speak_positive_affirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNumberOfCommitmentForNextWeekModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_no_of_food_commitments', models.IntegerField(blank=True, default=0)),
                ('min_no_of_water_commitments', models.IntegerField(blank=True, default=0)),
                ('min_no_of_exercise_commitments', models.IntegerField(blank=True, default=0)),
                ('min_no_of_challenges', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
