# Generated by Django 4.1.2 on 2023-08-04 14:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitment", "0006_alter_usercommitmentsfornextweekmodel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2023, 8, 6, 14, 56, 13, 118184)
            ),
        ),
    ]
