# Generated by Django 4.1.2 on 2022-10-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0006_alter_commitmentnamemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentnamemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentcategorymodel'),
        ),
    ]
