# Generated by Django 4.1.2 on 2023-01-04 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0007_alter_usernumberofcommitmentfornextweekmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='min_no_of_challenges',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='min_no_of_exercise_commitments',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='min_no_of_food_commitments',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='min_no_of_water_commitments',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
