# Generated by Django 4.1.2 on 2022-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0007_alter_commitmentnamemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentmodel',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
