# Generated by Django 4.1.2 on 2023-01-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_individualexercisemodel_and_more'),
        ('commitment', '0008_alter_usernumberofcommitmentfornextweekmodel_min_no_of_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='user',
            field=models.OneToOneField(blank=True, error_messages={'unique': 'User id is invalid'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
    ]
