# Generated by Django 4.1.2 on 2022-10-31 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0008_commitmentmodel_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseOfCategorySuccessOrFailureModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('is_success', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentcategorymodel')),
            ],
        ),
    ]
