# Generated by Django 4.1.2 on 2023-01-04 07:46

import commitment.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0009_alter_usernumberofcommitmentfornextweekmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 11, 7, 46, 57, 701294)),
        ),
        migrations.AddField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='start_date',
            field=models.DateField(blank=True, default=commitment.models.next_day_datetime),
        ),
    ]
