# Generated by Django 4.1.2 on 2023-01-04 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0013_alter_usernumberofcommitmentfornextweekmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 8, 7, 59, 18, 694804)),
        ),
    ]
