# Generated by Django 4.1.2 on 2023-01-04 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_individualexercisemodel_and_more'),
        ('commitment', '0014_alter_usernumberofcommitmentfornextweekmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 8, 8, 1, 21, 802948)),
        ),
        migrations.AlterField(
            model_name='usernumberofcommitmentfornextweekmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
    ]
