# Generated by Django 4.1.2 on 2023-04-17 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0022_alter_usercommitmentsfornextweekmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='number_of_positive_affirmations_to_display',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='usercommitmentsfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 23, 3, 7, 158421)),
        ),
    ]
