# Generated by Django 4.1.2 on 2023-04-17 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positive_affirmations', '__first__'),
        ('commitment', '0023_exercisemodel_number_of_positive_affirmations_to_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemodel',
            name='number_of_positive_affirmations_to_display',
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='positive_affirmations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='positive_affirmations.positiveaffirmationmodel'),
        ),
        migrations.AlterField(
            model_name='usercommitmentsfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 23, 9, 2, 540606)),
        ),
    ]
