# Generated by Django 4.1.2 on 2023-04-17 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0024_remove_exercisemodel_number_of_positive_affirmations_to_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemodel',
            name='positive_affirmations',
        ),
        migrations.AlterField(
            model_name='usercommitmentsfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 23, 15, 3, 356999)),
        ),
    ]
