# Generated by Django 4.1.2 on 2023-04-18 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0026_alter_usercommitmentsfornextweekmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentmodel',
            name='total_commitments_done',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usercommitmentsfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 5, 34, 48, 93379)),
        ),
    ]
