# Generated by Django 4.1.2 on 2023-04-20 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0027_commitmentmodel_total_commitments_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommitmentsfornextweekmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 11, 15, 37, 831587)),
        ),
    ]
