# Generated by Django 4.2.7 on 2023-12-09 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitment", "0066_alter_usercommitmentsfornextweekmodel_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercommitmentsfornextweekmodel",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2023, 12, 10, 10, 13, 12, 23878)
            ),
        ),
    ]
