# Generated by Django 4.1.2 on 2023-07-29 07:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soloCompetitionsForFreeTrialUsers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freetrialsolochallengesmodel",
            name="challenge_date",
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 30)),
        ),
    ]
