# Generated by Django 4.1.2 on 2023-08-15 12:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "soloCompetitionsForFreeTrialUsers",
            "0010_alter_freetrialsolochallengesmodel_challenge_date",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freetrialsolochallengesmodel",
            name="user",
        ),
        migrations.AlterField(
            model_name="freetrialsolochallengesmodel",
            name="challenge_date",
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 25)),
        ),
    ]
