# Generated by Django 4.1.2 on 2023-08-23 14:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "soloCompetitionsForFreeTrialUsers",
            "0011_remove_freetrialsolochallengesmodel_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="freetrialsolochallengesmodel",
            name="challenge_date",
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 2)),
        ),
    ]
