# Generated by Django 4.1.2 on 2023-09-01 15:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "soloCompetitionsForFreeTrialUsers",
            "0012_alter_freetrialsolochallengesmodel_challenge_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="freetrialsolochallengesmodel",
            name="challenge_date",
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 11)),
        ),
    ]
