# Generated by Django 4.1.2 on 2023-01-11 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChallengesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "challenge_name",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "challenge_video_url",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "challenge_title",
                    models.CharField(db_index=True, default="", max_length=80),
                ),
                ("challenge_image", models.FileField(blank=True, upload_to="")),
                ("min_age", models.IntegerField(blank=True, default=0)),
                ("max_age", models.IntegerField(blank=True, default=0)),
                ("start_date", models.DateField(blank=True)),
                ("end_date", models.DateField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantsInGroupChallengeModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge_video", models.FileField(blank=True, upload_to="")),
                ("has_submitted_video", models.BooleanField(default=False)),
                ("hide_from_user", models.BooleanField(default=False)),
                ("date_of_submission", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "group_challenge",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.groupchallengesmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
