# Generated by Django 4.1.2 on 2023-01-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_challenges", "0002_participantsingroupchallengemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsingroupchallengemodel",
            name="hide_from_user",
            field=models.BooleanField(default=False),
        ),
    ]
