# Generated by Django 4.1.2 on 2023-03-24 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenges', '0003_remove_rulesofgroupchallengemodel_group_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchallengesmodel',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
    ]
