# Generated by Django 4.1.2 on 2023-01-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_challenges", "0003_participantsingroupchallengemodel_hide_from_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantsingroupchallengemodel",
            name="date_of_submission",
            field=models.DateTimeField(blank=True),
        ),
    ]
