# Generated by Django 4.1.2 on 2023-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0004_groupchallengesmodel_is_limited_time_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="challenge_video_url",
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
