# Generated by Django 4.1.2 on 2023-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenges', '0004_groupchallengesmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchallengesmodel',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
