# Generated by Django 4.1.2 on 2023-01-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "group_challenges",
            "0004_alter_participantsingroupchallengemodel_date_of_submission",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantsingroupchallengemodel",
            name="date_of_submission",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
