# Generated by Django 4.1.2 on 2023-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenges', '0005_alter_groupchallengesmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchallengesmodel',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
