# Generated by Django 4.1.2 on 2023-08-12 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0006_logsofgroupchallengepagemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogsOfGroupChallengePageModel",
        ),
    ]
