# Generated by Django 4.1.2 on 2023-09-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0007_delete_logsofgroupchallengepagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchallengesmodel",
            name="is_bidding_challenge",
            field=models.BooleanField(default=False),
        ),
    ]
