# Generated by Django 4.1.2 on 2023-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0008_groupchallengesmodel_is_bidding_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchallengesmodel",
            name="max_participants_allowed",
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="groupchallengesmodel",
            name="price_to_pay",
            field=models.CharField(default="", max_length=10),
        ),
    ]
