# Generated by Django 4.1.2 on 2023-09-09 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_usermodel_api_key"),
        (
            "group_challenges",
            "0009_groupchallengesmodel_max_participants_allowed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BiddingChallengePaymentDetailsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_id", models.CharField(max_length=50)),
                (
                    "date_of_payment",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "group_challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.groupchallengesmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
