# Generated by Django 4.1.2 on 2023-09-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
        ("group_challenges", "0010_biddingchallengepaymentdetailsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchallengesmodel",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionmodel",
            ),
        ),
    ]
