# Generated by Django 4.1.2 on 2023-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0012_remove_groupchallengesmodel_designation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="max_participants_allowed",
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
    ]
