# Generated by Django 4.1.2 on 2023-09-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0014_groupchallengesmodel_created_by_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchallengesmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
