# Generated by Django 4.1.2 on 2023-09-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitment", "0046_alter_usercommitmentsfornextweekmodel_end_date"),
        ("subscription", "0002_remove_subscriptionmodel_designation_id"),
        ("user", "0004_alter_usermodel_api_key"),
        ("group_challenges", "0015_groupchallengesmodel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="challenge_video_url",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="price_to_pay",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionmodel",
            ),
        ),
        migrations.AlterField(
            model_name="groupchallengesmodel",
            name="suggested_workout",
            field=models.ManyToManyField(
                blank=True, to="commitment.commitmentnamemodel"
            ),
        ),
    ]
