# Generated by Django 4.1.2 on 2023-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "group_challenges",
            "0019_alter_participantsinpubliccustomgroupchallengesmodel_group_challenge_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsingroupchallengesforfreetrialmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
