# Generated by Django 4.1.2 on 2023-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "group_challenges",
            "0020_participantsingroupchallengesforfreetrialmodel_is_active",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="biddinggroupchallengesmodel",
            name="challenge_name",
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="groupchallengesforfreetrialmodel",
            name="challenge_name",
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="groupchallengesforsubscribedusersmodel",
            name="challenge_name",
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
