# Generated by Django 4.1.2 on 2023-09-24 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userpaymentdetailsmodel_subscription_end_date_and_more"),
        (
            "group_challenges",
            "0021_alter_biddinggroupchallengesmodel_challenge_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateCustomGroupChallengesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge_date", models.DateField(blank=True, null=True)),
                (
                    "total_participants",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "price_to_pay",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "challenge_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.publiccustomgroupchallengestitlemodel",
                    ),
                ),
                (
                    "host_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_user",
                        to="user.usermodel",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="participants_in_challenge", to="user.usermodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivateCustomGroupChallengesPaymentModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_id", models.CharField(max_length=50)),
                (
                    "date_of_payment",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "group_challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.privatecustomgroupchallengesmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
