# Generated by Django 4.1.2 on 2023-09-24 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0022_privatecustomgroupchallengesmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatecustomgroupchallengesmodel",
            name="user",
        ),
    ]
