# Generated by Django 4.1.2 on 2023-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group_challenges", "0023_remove_privatecustomgroupchallengesmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatecustomgroupchallengesmodel",
            name="total_participants",
        ),
    ]
