# Generated by Django 4.1.2 on 2023-09-27 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userpaymentdetailsmodel_subscription_end_date_and_more"),
        (
            "group_challenges",
            "0024_remove_privatecustomgroupchallengesmodel_total_participants",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatecustomgroupchallengesmodel",
            name="participants",
        ),
        migrations.CreateModel(
            name="ParticipantsInPrivateCustomGroupChallengesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge_video", models.FileField(blank=True, upload_to="")),
                ("has_submitted_video", models.BooleanField(default=False)),
                ("hide_from_user", models.BooleanField(default=False)),
                ("date_of_submission", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "group_challenge",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.privatecustomgroupchallengesmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
