# Generated by Django 4.1.2 on 2023-09-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "group_challenges",
            "0025_remove_privatecustomgroupchallengesmodel_participants_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsinprivatecustomgroupchallengesmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
