# Generated by Django 4.1.2 on 2023-09-30 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userpaymentdetailsmodel_subscription_end_date_and_more"),
        ("commitment", "0058_alter_usercommitmentsfornextweekmodel_end_date"),
        ("subscription", "0003_remove_subscriptionmodel_is_free_trial"),
        (
            "group_challenges",
            "0026_participantsinprivatecustomgroupchallengesmodel_is_active",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChallengeModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge_name", models.CharField(db_index=True, max_length=80)),
                (
                    "challenge_video_url",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "challenge_title",
                    models.CharField(db_index=True, default="", max_length=80),
                ),
                ("challenge_image", models.FileField(blank=True, upload_to="")),
                ("time_in_seconds", models.IntegerField(default=0)),
                ("is_limited_time_challenge", models.BooleanField(default=False)),
                ("challenge_date", models.DateField(blank=True, null=True)),
                (
                    "max_participants_allowed",
                    models.IntegerField(blank=True, default=0, max_length=10),
                ),
                (
                    "price_to_pay",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupChallengesPaymentModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_id", models.CharField(max_length=50)),
                (
                    "date_of_payment",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupChallengeTypeModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(db_index=True, max_length=80)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantsInGroupChallengesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge_video", models.FileField(blank=True, upload_to="")),
                ("has_submitted_video", models.BooleanField(default=False)),
                ("hide_from_user", models.BooleanField(default=False)),
                ("date_of_submission", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "challenge_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.groupchallengetypemodel",
                    ),
                ),
                (
                    "group_challenge",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_challenges.groupchallengemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="biddinggroupchallengesmodel",
            name="suggested_workout",
        ),
        migrations.RemoveField(
            model_name="groupchallengesforfreetrialmodel",
            name="suggested_workout",
        ),
        migrations.RemoveField(
            model_name="groupchallengesforsubscribedusersmodel",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="groupchallengesforsubscribedusersmodel",
            name="suggested_workout",
        ),
        migrations.RemoveField(
            model_name="participantsinbiddinggroupchallengesmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="participantsinbiddinggroupchallengesmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="participantsingroupchallengesforfreetrialmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="participantsingroupchallengesforfreetrialmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="participantsingroupchallengesforsubscribedusersmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="participantsingroupchallengesforsubscribedusersmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="participantsinprivatecustomgroupchallengesmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="participantsinprivatecustomgroupchallengesmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="participantsinpubliccustomgroupchallengesmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="participantsinpubliccustomgroupchallengesmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="privatecustomgroupchallengesmodel",
            name="challenge_details",
        ),
        migrations.RemoveField(
            model_name="privatecustomgroupchallengesmodel",
            name="host_user",
        ),
        migrations.RemoveField(
            model_name="privatecustomgroupchallengespaymentmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="privatecustomgroupchallengespaymentmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="publiccustomgroupchallengesmodel",
            name="challenge_details",
        ),
        migrations.RemoveField(
            model_name="publiccustomgroupchallengesmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="publiccustomgroupchallengespaymentmodel",
            name="group_challenge",
        ),
        migrations.RemoveField(
            model_name="publiccustomgroupchallengespaymentmodel",
            name="user",
        ),
        migrations.DeleteModel(
            name="BiddingChallengePaymentDetailsModel",
        ),
        migrations.DeleteModel(
            name="BiddingGroupChallengesModel",
        ),
        migrations.DeleteModel(
            name="GroupChallengesForFreeTrialModel",
        ),
        migrations.DeleteModel(
            name="GroupChallengesForSubscribedUsersModel",
        ),
        migrations.DeleteModel(
            name="ParticipantsInBiddingGroupChallengesModel",
        ),
        migrations.DeleteModel(
            name="ParticipantsInGroupChallengesForFreeTrialModel",
        ),
        migrations.DeleteModel(
            name="ParticipantsInGroupChallengesForSubscribedUsersModel",
        ),
        migrations.DeleteModel(
            name="ParticipantsInPrivateCustomGroupChallengesModel",
        ),
        migrations.DeleteModel(
            name="ParticipantsInPublicCustomGroupChallengesModel",
        ),
        migrations.DeleteModel(
            name="PrivateCustomGroupChallengesModel",
        ),
        migrations.DeleteModel(
            name="PrivateCustomGroupChallengesPaymentModel",
        ),
        migrations.DeleteModel(
            name="PublicCustomGroupChallengesModel",
        ),
        migrations.DeleteModel(
            name="PublicCustomGroupChallengesPaymentModel",
        ),
        migrations.AddField(
            model_name="groupchallengespaymentmodel",
            name="challenge_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group_challenges.groupchallengetypemodel",
            ),
        ),
        migrations.AddField(
            model_name="groupchallengespaymentmodel",
            name="group_challenge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group_challenges.groupchallengemodel",
            ),
        ),
        migrations.AddField(
            model_name="groupchallengespaymentmodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="groupchallengemodel",
            name="challenge_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group_challenges.groupchallengetypemodel",
            ),
        ),
        migrations.AddField(
            model_name="groupchallengemodel",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionmodel",
            ),
        ),
        migrations.AddField(
            model_name="groupchallengemodel",
            name="suggested_workout",
            field=models.ManyToManyField(
                blank=True, to="commitment.commitmentnamemodel"
            ),
        ),
    ]
