# Generated by Django 4.1.2 on 2023-10-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "group_challenges",
            "0028_alter_groupchallengemodel_max_participants_allowed",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchallengemodel",
            name="max_participants_allowed",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
