# Generated by Django 4.1.2 on 2022-12-07 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('designation_id', models.IntegerField(blank=True, default=0)),
                ('is_free_trial', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
