# Generated by Django 4.1.2 on 2023-07-29 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionLevelModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("level", models.CharField(default="", max_length=30)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.BigIntegerField()),
                (
                    "designation_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "refund_amount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_free_trial", models.BooleanField(default=False)),
                ("is_call_service_included", models.BooleanField(default=False)),
                ("duration", models.CharField(blank=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "level_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscriptionlevelmodel",
                    ),
                ),
            ],
        ),
    ]
