# Generated by Django 4.1.2 on 2022-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='designation_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
