# Generated by Django 4.1.2 on 2022-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionlevelmodel_subscriptionmodel_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='designation_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
