# Generated by Django 4.1.2 on 2023-01-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_subscriptionmodel_is_call_service_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionmodel",
            name="refund_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
