# Generated by Django 4.1.2 on 2023-09-19 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_remove_subscriptionmodel_designation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionmodel",
            name="is_free_trial",
        ),
    ]
