# Generated by Django 4.1.2 on 2023-03-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionmodel_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
