branch-defaults:
  master_same_database:
    environment: commdem-warriors-same-database-dev
    group_suffix: null
global:
  application_name: commdem_warriors_same_database
  branch: null
  default_ec2_keyname: commdemWarriors
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
