# Generated by Django 4.1.2 on 2023-08-06 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commitment", "0013_alter_usercommitmentsfornextweekmodel_end_date"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarriorsWorkoutVideosModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=200)),
                ("workout_file", models.FileField(blank=True, upload_to="")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_private_for_all", models.BooleanField(default=False)),
                (
                    "private_for_this_gender",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.commitmentmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserWiseWorkoutVideosPrivacyModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_private", models.BooleanField(default=False)),
                (
                    "fromUser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to="user.usermodel",
                    ),
                ),
                (
                    "toUser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
                (
                    "workoutVideo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warriors_workout_videos.warriorsworkoutvideosmodel",
                    ),
                ),
            ],
        ),
    ]
