# Generated by Django 4.1.2 on 2023-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warriors_workout_videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warriorsworkoutvideosmodel",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="warriorsworkoutvideosmodel",
            name="workout_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
