# Generated by Django 4.1.2 on 2023-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warriors_workout_videos",
            "0004_alter_warriorsworkoutvideosmodel_private_for_this_gender",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="warriorsworkoutvideosmodel",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
