# Generated by Django 4.1.2 on 2023-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warriors_workout_videos",
            "0005_alter_warriorsworkoutvideosmodel_description",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="warriorsworkoutvideosmodel",
            name="workout_thumbnail_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
