# Generated by Django 4.1.2 on 2023-10-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bidding_contest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersofbiddingcontestmodel",
            name="bidding_contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bidding_contest.biddingcontestmodel",
            ),
        ),
    ]
