# Generated by Django 4.2.7 on 2023-12-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_usermodel_mobile_number"),
        ("bidding_contest", "0002_answersofbiddingcontestmodel_bidding_contest"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiddingContestResultModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rank", models.IntegerField(blank=True, default=0)),
                ("prize_money", models.IntegerField(blank=True, default=0)),
                ("description", models.CharField(default="", max_length=200)),
                ("is_payment_done", models.BooleanField(default=False)),
                (
                    "payment_transaction_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "bidding_contest",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding_contest.biddingcontestmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
