# Generated by Django 4.1.2 on 2023-07-29 06:19

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChatModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chat_message",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "Files",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FileField(blank=True, upload_to=""),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_message_seen_by_all", models.BooleanField(default=False)),
                ("is_first_message_of_day", models.BooleanField(default=False)),
                ("files_path", models.FileField(blank=True, upload_to="")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user_detail",
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
