# Generated by Django 4.1.2 on 2023-02-19 10:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_userwiseprivacymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_message', models.CharField(blank=True, default='', max_length=2000)),
                ('is_message_seen_by_all', models.BooleanField(default=False)),
                ('files_path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_detail', to='user.usermodel')),
            ],
        ),
    ]
