# Generated by Django 4.1.2 on 2023-02-19 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupChatModule', '0002_alter_groupchatmodel_files_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmodel',
            name='files_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100, null=True), blank=True, default=list, size=None),
        ),
    ]
