# Generated by Django 4.1.2 on 2023-04-16 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupChatModule', '0005_groupchatmodel_is_first_message_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmodel',
            name='Files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to=''), blank=True, default=list, null=True, size=None),
        ),
    ]
