# Generated by Django 4.1.2 on 2023-07-29 06:20

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisementModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("person_name", models.CharField(max_length=100)),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True, max_length=128, region=None
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                ("image_url", models.CharField(max_length=300)),
                ("video_url", models.CharField(max_length=300)),
                ("logo", models.FileField(blank=True, upload_to="")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdvertiserModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "advertisement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.advertisementmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvertisementViewsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("view_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "advertisement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.advertisementmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvertisementClicksModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "click_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "advertisement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.advertisementmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
