# Generated by Django 4.1.2 on 2023-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisementmodel",
            name="has_sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
