# Generated by Django 4.1.2 on 2023-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0002_advertisementmodel_has_sponsored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisementmodel",
            name="image_url",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="advertisementmodel",
            name="video_url",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
