# Generated by Django 4.2.7 on 2023-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0003_alter_advertisementmodel_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisementmodel",
            name="mobile_number",
            field=models.CharField(db_index=True),
        ),
    ]
