# Generated by Django 4.1.2 on 2023-04-20 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0029_alter_advertisementmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 27, 12, 33, 21, 516804)),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 21, 12, 33, 21, 516783)),
        ),
    ]
