# Generated by Django 4.1.2 on 2022-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeemPoints', '0002_redeempointsmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeempointsmodel',
            name='from_user_ids',
        ),
        migrations.AddField(
            model_name='redeempointsmodel',
            name='from_user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
