# Generated by Django 4.1.2 on 2023-07-29 06:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commitment", "0002_alter_usercommitmentsfornextweekmodel_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLevelModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "level_name",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "workout_video_url",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "workout_title",
                    models.CharField(db_index=True, default="", max_length=80),
                ),
                ("workout_image", models.FileField(blank=True, upload_to="")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "level_of_workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutlevelmodel",
                    ),
                ),
                (
                    "workout_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.commitmentnamemodel",
                    ),
                ),
            ],
        ),
    ]
