# Generated by Django 4.1.2 on 2023-07-29 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("designation", "0001_initial"),
        ("commitment", "0003_alter_usercommitmentsfornextweekmodel_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="voiceAssistantLanguagesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("languageName", models.CharField(max_length=30)),
                ("languageCode", models.CharField(max_length=5)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="voiceAssistantBeforeUpdateMessageModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("age_group", models.CharField(blank=True, max_length=100)),
                (
                    "no_of_times_in_current_week",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "range_of_success_of_commitment_name_in_this_week",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_it_weekend", models.BooleanField(default=True)),
                ("voice_assistant_message", models.CharField(max_length=400)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "commitment_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.commitmentcategorymodel",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="designation.designationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="voiceAssistantAfterUpdateMessageModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("voice_assistant_message", models.CharField(max_length=400)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "commitment_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.commitmentcategorymodel",
                    ),
                ),
                (
                    "reason_behind_commitment_success_or_failure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.causeofcategorysuccessorfailuremodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userPreferredVoiceLanguageModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
                (
                    "voice_assistant_language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voiceAssistant.voiceassistantlanguagesmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userCommitmentVoiceBeforeUpdateModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("audio_file_path", models.FileField(blank=True, upload_to="")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "commitment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.commitmentmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
