# Generated by Django 4.1.2 on 2022-12-17 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0001_initial'),
        ('user', '0005_keystoupdateinfrontendmodel_is_commitment_table_updated'),
        ('voiceAssistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCommitmentVoiceBeforeUpdateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_file_path', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('commitment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
