# Generated by Django 4.1.2 on 2022-12-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0002_usercommitmentvoicebeforeupdatemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiceassistantlanguagesmodel',
            old_name='language_code',
            new_name='languageCode',
        ),
        migrations.RenameField(
            model_name='voiceassistantlanguagesmodel',
            old_name='language_name',
            new_name='languageName',
        ),
    ]
