# Generated by Django 4.1.2 on 2022-12-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0003_rename_language_code_voiceassistantlanguagesmodel_languagecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommitmentvoicebeforeupdatemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
