# Generated by Django 4.1.2 on 2022-12-23 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0004_alter_usercommitmentvoicebeforeupdatemodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='voiceAssistantMessageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commitment_category_id', models.IntegerField(blank=True, default=0)),
                ('commitment_category_name', models.IntegerField(blank=True, default=0)),
                ('reason_behind_commitment_success_or_failure_id', models.IntegerField(blank=True, default=0)),
                ('no_of_week_from_date_of_joining', models.IntegerField(blank=True, default=0)),
                ('no_of_times_in_current_week', models.IntegerField(blank=True, default=0)),
                ('range_of_success_of_commitment_name', models.CharField(blank=True, max_length=100)),
                ('range_of_current_week_success_of_commitment_category', models.CharField(blank=True, max_length=100)),
                ('is_it_weekend', models.BooleanField(default=True)),
                ('voice_assistant_message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
