# Generated by Django 4.1.2 on 2022-12-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0001_initial'),
        ('voiceAssistant', '0005_voiceassistantmessagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceassistantmessagemodel',
            name='commitment_category_id',
        ),
        migrations.RemoveField(
            model_name='voiceassistantmessagemodel',
            name='commitment_category_name',
        ),
        migrations.RemoveField(
            model_name='voiceassistantmessagemodel',
            name='reason_behind_commitment_success_or_failure_id',
        ),
        migrations.AddField(
            model_name='voiceassistantmessagemodel',
            name='commitment_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentcategorymodel'),
        ),
        migrations.AddField(
            model_name='voiceassistantmessagemodel',
            name='commitment_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentnamemodel'),
        ),
        migrations.AddField(
            model_name='voiceassistantmessagemodel',
            name='reason_behind_commitment_success_or_failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.reasonbehindcommitmentsuccessorfailureforuser'),
        ),
    ]
