# Generated by Django 4.1.2 on 2022-12-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0006_remove_voiceassistantmessagemodel_commitment_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceassistantmessagemodel',
            name='is_listening_today',
            field=models.BooleanField(default=True),
        ),
    ]
