# Generated by Django 4.1.2 on 2022-12-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0008_voiceassistantafterupdatemessagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='no_of_days_from_joining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            name='no_of_days_from_joining',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
