# Generated by Django 4.1.2 on 2022-12-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('voiceAssistant', '0009_voiceassistantafterupdatemessagemodel_no_of_days_from_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='age_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.designationmodel'),
        ),
        migrations.AddField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            name='age_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.designationmodel'),
        ),
    ]
