# Generated by Django 4.1.2 on 2022-12-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0010_voiceassistantafterupdatemessagemodel_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            name='no_of_days_from_joining',
        ),
    ]
