# Generated by Django 4.1.2 on 2022-12-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0011_remove_voiceassistantbeforeupdatemessagemodel_no_of_days_from_joining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            old_name='range_of_success_of_commitment_name',
            new_name='range_of_success_of_commitment_name_in_this_week',
        ),
    ]
