# Generated by Django 4.1.2 on 2022-12-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0013_alter_voiceassistantbeforeupdatemessagemodel_voice_assistant_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            name='commitment_name',
        ),
        migrations.RemoveField(
            model_name='voiceassistantbeforeupdatemessagemodel',
            name='no_of_week_from_date_of_joining',
        ),
    ]
