# Generated by Django 4.1.2 on 2022-12-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0014_remove_voiceassistantbeforeupdatemessagemodel_commitment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiceassistantafterupdatemessagemodel',
            old_name='no_of_days_from_joining',
            new_name='no_of_times_this_reason_in_current_week',
        ),
        migrations.RenameField(
            model_name='voiceassistantafterupdatemessagemodel',
            old_name='range_of_current_week_success_of_commitment_category',
            new_name='range_of_success_of_exercise_in_this_week',
        ),
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='commitment_name',
        ),
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='no_of_times_in_current_week',
        ),
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='no_of_week_from_date_of_joining',
        ),
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='range_of_success_of_commitment_name',
        ),
    ]
