# Generated by Django 4.1.2 on 2022-12-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0001_initial'),
        ('voiceAssistant', '0015_rename_no_of_days_from_joining_voiceassistantafterupdatemessagemodel_no_of_times_this_reason_in_curr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='reason_behind_commitment_success_or_failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.causeofcategorysuccessorfailuremodel'),
        ),
    ]
