# Generated by Django 4.1.2 on 2022-12-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0016_alter_voiceassistantafterupdatemessagemodel_reason_behind_commitment_success_or_failure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='is_it_weekend',
        ),
    ]
