# Generated by Django 4.1.2 on 2022-12-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0017_remove_voiceassistantafterupdatemessagemodel_is_it_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='occupation',
        ),
    ]
