# Generated by Django 4.1.2 on 2022-12-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAssistant', '0020_alter_voiceassistantafterupdatemessagemodel_voice_assistant_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceassistantafterupdatemessagemodel',
            name='range_of_success_of_exercise_in_this_week',
        ),
    ]
