# Generated by Django 4.1.2 on 2023-01-19 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("oneToOneChatModule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetoonechatmodel",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="onetoonechatmodel",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
