# Generated by Django 4.1.2 on 2023-01-19 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("oneToOneChatModule", "0002_alter_onetoonechatmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetoonechatmodel",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="onetoonechatmodel",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
