# Generated by Django 4.1.2 on 2023-01-20 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneToOneChatModule', '0004_alter_onetoonechatmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoonechatmodel',
            name='is_message_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onetoonechatmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onetoonechatmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
