# Generated by Django 4.1.2 on 2023-07-29 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mcqsChoicesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="", max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionsToAskBeforeModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("main_question", models.CharField(default="", max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "mcqs",
                    models.ManyToManyField(
                        to="questions_before_relationship.mcqschoicesmodel"
                    ),
                ),
            ],
        ),
    ]
