# Generated by Django 4.1.2 on 2022-12-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
