# Generated by Django 4.1.2 on 2023-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referralCode", "0002_remove_referralcodemodel_referral_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralcodemodel",
            name="is_payment_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="referralcodemodel",
            name="payment_transaction_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
