# Generated by Django 4.1.2 on 2022-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralCode', '0002_referralcodemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodemodel',
            name='referred_user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
