# Generated by Django 4.1.2 on 2022-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralCode', '0003_referralcodemodel_referred_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcodemodel',
            name='referred_user_id',
        ),
    ]
