# Generated by Django 4.1.2 on 2023-08-12 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogsOfUserProgressTapModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user",
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogsOfPagesOfUserModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_challenges_page", models.IntegerField(blank=True, default=0)),
                ("subscriptions_page", models.IntegerField(blank=True, default=0)),
                ("add_commitment_page", models.IntegerField(blank=True, default=0)),
                (
                    "performsers_of_the_week_page",
                    models.IntegerField(blank=True, default=0),
                ),
                ("dashboard_page", models.IntegerField(blank=True, default=0)),
                ("otp_page", models.IntegerField(blank=True, default=0)),
                (
                    "individual_user_performance_page",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
