# Generated by Django 4.1.2 on 2023-08-12 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logsofpagesofusermodel",
            old_name="performsers_of_the_week_page",
            new_name="performers_of_the_week_page",
        ),
    ]
