# Generated by Django 4.1.2 on 2023-08-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logs",
            "0002_rename_performsers_of_the_week_page_logsofpagesofusermodel_performers_of_the_week_page",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="logsofuserprogresstapmodel",
            name="number_of_times",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
