# Generated by Django 4.1.2 on 2023-08-12 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0003_alter_advertisementmodel_image_url_and_more"),
        ("user", "0001_initial"),
        ("logs", "0003_logsofuserprogresstapmodel_number_of_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogsOfUserTapOnAdvertisementModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number_of_times", models.IntegerField(blank=True, default=0)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.advertisementmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
