# Generated by Django 4.1.2 on 2023-01-04 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseLevelModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "level_name",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
