# Generated by Django 4.1.2 on 2023-01-04 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("commitment", "0005_exercisemodel_did_speak_positive_affirmation"),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseWiseChallengesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "challenge_name",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitment.commitmentnamemodel",
                    ),
                ),
                (
                    "level_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.exerciselevelmodel",
                    ),
                ),
            ],
        ),
    ]
