# Generated by Django 4.1.2 on 2023-01-05 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0020_alter_usernumberofcommitmentfornextweekmodel_end_date'),
        ('challenges', '0003_exercisewisechallengesmodel_challenge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutWiseChallengesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_video_url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('workout_image', models.FileField(blank=True, upload_to='')),
                ('challenge_name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('challenge_video_url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('challenge_image', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='ExerciseLevelModel',
            new_name='WorkoutLevelModel',
        ),
        migrations.DeleteModel(
            name='ExerciseWiseChallengesModel',
        ),
        migrations.AddField(
            model_name='workoutwisechallengesmodel',
            name='level_of_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.workoutlevelmodel'),
        ),
        migrations.AddField(
            model_name='workoutwisechallengesmodel',
            name='workout_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitment.commitmentnamemodel'),
        ),
    ]
