# Generated by Django 4.1.2 on 2023-01-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_remove_workoutwisechallengesmodel_challenge_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutwisechallengesmodel',
            name='challenge_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='workoutwisechallengesmodel',
            name='challenge_video_url',
            field=models.CharField(db_index=True, default='', max_length=80, unique=True),
        ),
    ]
