# Generated by Django 4.1.2 on 2023-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_workoutwisechallengesmodel_challenge_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutwisechallengesmodel',
            name='workout_title',
            field=models.CharField(db_index=True, default='', max_length=80),
        ),
    ]
