# Generated by Django 4.1.2 on 2023-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0008_alter_workoutwisechallengesmodel_challenge_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutwisechallengesmodel",
            name="challenge_title",
            field=models.CharField(db_index=True, default="", max_length=80),
        ),
    ]
