# Generated by Django 4.1.2 on 2023-01-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0009_workoutwisechallengesmodel_challenge_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutwisechallengesmodel", name="challenge_title",
        ),
    ]
