# Generated by Django 4.1.2 on 2023-01-17 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWisePrivacyModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_my_age_hidden", models.BooleanField(default=True)),
                ("is_my_city_hidden", models.BooleanField(default=True)),
                ("is_my_mobile_number_hidden", models.BooleanField(default=True)),
                ("is_my_designation_title_hidden", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "my_details",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_user_details",
                        to="user.usermodel",
                    ),
                ),
                (
                    "other_user_details",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
