# Generated by Django 4.1.2 on 2023-09-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_usermodel_referred_user_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(default="", max_length=40),
        ),
    ]
