# Generated by Django 4.1.2 on 2023-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userwiseprivacymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
