# Generated by Django 4.1.2 on 2022-12-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_keystoupdateinfrontendmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='keysToUpdateInFrontEndModel',
        ),
    ]
