# Generated by Django 4.1.2 on 2022-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationdetailsmodel',
            name='city_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
