# Generated by Django 4.1.2 on 2022-10-19 08:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
