# Generated by Django 4.1.2 on 2023-09-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_usermodel_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(default="", max_length=64),
        ),
    ]
