# Generated by Django 4.1.2 on 2022-12-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_keystoupdateinfrontendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystoupdateinfrontendmodel',
            name='is_commitment_table_updated',
            field=models.BooleanField(default=False),
        ),
    ]
