# Generated by Django 4.1.2 on 2023-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.FilePathField(blank=True),
        ),
    ]
