# Generated by Django 4.2.7 on 2023-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userpaymentdetailsmodel_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="mobile_number",
            field=models.CharField(
                db_index=True,
                error_messages={
                    "unique": "This mobile number already exists in our database"
                },
                unique=True,
            ),
        ),
    ]
