# Generated by Django 4.1.2 on 2022-10-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userpaymentdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
