# Generated by Django 4.1.2 on 2022-12-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
        ('designation', '0001_initial'),
        ('user', '0005_keystoupdateinfrontendmodel_is_commitment_table_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofessionaldetailsmodel',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='userprofessionaldetailsmodel',
            name='income_range_id',
        ),
        migrations.AddField(
            model_name='userprofessionaldetailsmodel',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.designationmodel'),
        ),
        migrations.AddField(
            model_name='userprofessionaldetailsmodel',
            name='income_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income.incomemodel'),
        ),
    ]
