# Generated by Django 4.1.2 on 2022-12-23 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofessionaldetailsmodel_designation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCashbackModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
