# Generated by Django 4.1.2 on 2023-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthdetailsmodel',
            name='number_of_positive_affirmations',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
