# Generated by Django 4.1.2 on 2023-01-03 06:32

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_usercashbackmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_pic",
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
