# Generated by Django 4.1.2 on 2023-01-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_usermodel_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_pic",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
