# Generated by Django 4.1.2 on 2023-04-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userhealthdetailsmodel_number_of_positive_affirmations'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
