# Generated by Django 4.1.2 on 2023-04-20 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('user', '0009_usermodel_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star_rating', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('review_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
