# Generated by Django 4.1.2 on 2023-01-03 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_usermodel_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelOfExerciseModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.IntegerField(blank=True, default=0)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualExerciseModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=30)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "level_of_exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.levelofexercisemodel",
                    ),
                ),
            ],
        ),
    ]
