# Generated by Django 4.1.2 on 2023-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userreviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewmodel',
            name='review_date',
            field=models.DateField(blank=True),
        ),
    ]
