# Generated by Django 4.1.2 on 2023-01-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_levelofexercisemodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualExerciseModel',
        ),
        migrations.DeleteModel(
            name='LevelOfExerciseModel',
        ),
    ]
