# Generated by Django 4.1.2 on 2023-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('user', '0011_alter_userreviewmodel_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviewmodel',
            name='review',
        ),
        migrations.AddField(
            model_name='userreviewmodel',
            name='review',
            field=models.ManyToManyField(to='reviews.reviewmodel'),
        ),
    ]
