# Generated by Django 4.1.2 on 2023-04-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('user', '0012_remove_userreviewmodel_review_userreviewmodel_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviewmodel',
            name='review',
        ),
        migrations.AddField(
            model_name='userreviewmodel',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewmodel'),
        ),
    ]
