# Generated by Django 4.1.2 on 2023-01-06 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_userpaymentdetailsmodel_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_age_hidden', models.BooleanField(default=False)),
                ('is_city_hidden', models.BooleanField(default=False)),
                ('is_mobile_number_hidden', models.BooleanField(default=False)),
                ('is_designation_title_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
