# Generated by Django 4.1.2 on 2023-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userprivacymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacymodel',
            name='is_age_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprivacymodel',
            name='is_city_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprivacymodel',
            name='is_designation_title_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprivacymodel',
            name='is_mobile_number_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
