# Generated by Django 4.1.2 on 2023-07-29 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PositiveAffirmationModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=200, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAffirmationModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "number_of_commitment_for_week_id",
                    models.IntegerField(blank=True, default=0),
                ),
                ("user_id", models.IntegerField(blank=True, default=0)),
                ("did_user_speak", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
