# Generated by Django 4.1.2 on 2023-01-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive_affirmations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiveaffirmationmodel',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
        ),
    ]
