# Generated by Django 4.1.2 on 2023-01-04 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_individualexercisemodel_and_more'),
        ('positive_affirmations', '0002_alter_positiveaffirmationmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAffirmationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=200, unique=True)),
                ('did_user_speak', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
