# Generated by Django 4.1.2 on 2023-01-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positive_affirmations', '0003_useraffirmationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraffirmationmodel',
            name='name',
        ),
    ]
