# Generated by Django 4.1.2 on 2023-01-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0018_alter_usernumberofcommitmentfornextweekmodel_end_date'),
        ('positive_affirmations', '0004_remove_useraffirmationmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraffirmationmodel',
            name='number_of_commitment_for_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commitment.usernumberofcommitmentfornextweekmodel'),
        ),
    ]
