# Generated by Django 4.1.2 on 2022-12-14 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfFoodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_food_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('food_image', models.FileField(blank=True, upload_to='')),
                ('is_for_weight_loss', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=False)),
                ('youtube_url', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('type_of_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.typeoffoodmodel')),
            ],
        ),
    ]
