# name: Django Deployment

# on:
#   push:
#     branches:
#       - master  # Change to your branch name

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa

#       - name: Configure known hosts
#         run: |
#           ssh-keyscan 43.205.115.157 >> ~/.ssh/known_hosts

#       - name: Copy deployment script
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#         run: |
#           sudo echo "$SSH_PRIVATE_KEY" > private_key.pem
#           chmod 600 private_key.pem
#           scp -i private_key.pem deploy.sh ubuntu@43.205.115.157:/tmp
#           ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@your-ec2-ip "bash /tmp/deploy.sh"

